// Auth types start

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Get new access token from refresh start

export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

// Get new access token from refresh end

export const LOGOUT = 'LOGOUT';
export const OPEN_CLOSE_SIDEBAR = 'OPEN_CLOSE_SIDEBAR';


// Auth types end

// Skill types start

export const GET_SKILLS_REQUEST = 'GET_SKILLS_REQUEST';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAILURE = 'GET_SKILLS_FAILURE';

export const ADD_SKILL_REQUEST = 'ADD_SKILL_REQUEST';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAILURE = 'ADD_SKILL_FAILURE';

export const DELETE_SKILL_REQUEST = 'DELETE_SKILL_REQUEST';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAILURE = 'DELETE_SKILL_FAILURE';

export const GET_SKILL_REQUEST = 'GET_SKILL_REQUEST';
export const GET_SKILL_SUCCESS = 'GET_SKILL_SUCCESS';
export const GET_SKILL_FAILURE = 'GET_SKILL_FAILURE';

export const EDIT_SKILL_REQUEST = 'EDIT_SKILL_REQUEST';
export const EDIT_SKILL_SUCCESS = 'EDIT_SKILL_SUCCESS';
export const EDIT_SKILL_FAILURE = 'EDIT_SKILL_FAILURE';

export const GET_SKILL_TOPICS_REQUEST = 'GET_SKILL_TOPICS_REQUEST';
export const GET_SKILL_TOPICS_SUCCESS = 'GET_SKILL_TOPICS_SUCCESS';
export const GET_SKILL_TOPICS_FAILURE = 'GET_SKILL_TOPICS_FAILURE';

// Skill types end


// Skill Topic types start

export const GET_TOPIC_REQUEST = 'GET_TOPIC_REQUEST';
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS';
export const GET_TOPIC_FAILURE = 'GET_TOPIC_FAILURE';

export const ADD_TOPIC_REQUEST = 'ADD_TOPIC_REQUEST';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_FAILURE = 'ADD_TOPIC_FAILURE';

export const EDIT_TOPIC_REQUEST = 'EDIT_TOPIC_REQUEST';
export const EDIT_TOPIC_SUCCESS = 'EDIT_TOPIC_SUCCESS';
export const EDIT_TOPIC_FAILURE = 'EDIT_TOPIC_FAILURE';

export const CHANGE_TOPIC_ORDERING_REQUEST = 'CHANGE_TOPIC_ORDERING_REQUEST';
export const CHANGE_TOPIC_ORDERING_SUCCESS = 'CHANGE_TOPIC_ORDERING_SUCCESS';
export const CHANGE_TOPIC_ORDERING_FAILURE = 'CHANGE_TOPIC_ORDERING_FAILURE';

export const DELETE_SKILL_TOPIC_REQUEST = 'DELETE_SKILL_TOPIC_REQUEST';
export const DELETE_SKILL_TOPIC_SUCCESS = 'DELETE_SKILL_TOPIC_SUCCESS';
export const DELETE_SKILL_TOPIC_FAILURE = 'DELETE_SKILL_TOPIC_FAILURE';

// Skill Topic types end

// Skill Questions types start

export const GET_SKILL_QUESTIONS_REQUEST = 'GET_SKILL_QUESTIONS_REQUEST';
export const GET_SKILL_QUESTIONS_SUCCESS = 'GET_SKILL_QUESTIONS_SUCCESS';
export const GET_SKILL_QUESTIONS_FAILURE = 'GET_SKILL_QUESTIONS_FAILURE';

export const DELETE_SKILL_QUESTION_REQUEST = 'DELETE_SKILL_QUESTION_REQUEST';
export const DELETE_SKILL_QUESTION_SUCCESS = 'DELETE_SKILL_QUESTION_SUCCESS';
export const DELETE_SKILL_QUESTION_FAILURE = 'DELETE_SKILL_QUESTION_FAILURE';

// Skill Questions types end

// Categories types start

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const ADD_CATEGORIES_REQUEST = 'ADD_CATEGORIES_REQUEST';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const ADD_CATEGORIES_FAILURE = 'ADD_CATEGORIES_FAILURE';


export const EDIT_CATEGORIES_REQUEST = 'EDIT_CATEGORIES_REQUEST';
export const EDIT_CATEGORIES_SUCCESS = 'EDIT_CATEGORIES_SUCCESS';
export const EDIT_CATEGORIES_FAILURE = 'EDIT_CATEGORIES_FAILURE';

export const DELETE_CATEGORIES_REQUEST = 'DELETE_CATEGORIES_REQUEST';
export const DELETE_CATEGORIES_SUCCESS = 'DELETE_CATEGORIES_SUCCESS';
export const DELETE_CATEGORIES_FAILURE = 'DELETE_CATEGORIES_FAILURE';

// Categories types end

//  University types start

export const ADD_UNIVERSITY_REQUEST = 'ADD_UNIVERSITY_REQUEST';
export const ADD_UNIVERSITY_SUCCESS = 'ADD_UNIVERSITY_SUCCESS';
export const ADD_UNIVERSITY_FAILURE = 'ADD_UNIVERSITY_FAILURE';

export const GET_UNIVERSITIES_REQUEST = 'GET_UNIVERSITIES_REQUEST';
export const GET_UNIVERSITIES_SUCCESS = 'GET_UNIVERSITIES_SUCCESS';
export const GET_UNIVERSITIES_FAILURE = 'GET_UNIVERSITIES_FAILURE';

export const EDIT_UNIVERSITY_REQUEST = 'EDIT_UNIVERSITY_REQUEST';
export const EDIT_UNIVERSITY_SUCCESS = 'EDIT_UNIVERSITY_SUCCESS';
export const EDIT_UNIVERSITY_FAILURE = 'EDIT_UNIVERSITY_FAILURE';

export const DELETE_UNIVERSITY_REQUEST = 'DELETE_UNIVERSITY_REQUEST';
export const DELETE_UNIVERSITY_SUCCESS = 'DELETE_UNIVERSITY_SUCCESS';
export const DELETE_UNIVERSITY_FAILURE = 'DELETE_UNIVERSITY_FAILURE';

// University types end